#!/usr/bin/env bash
# Integration preset wrapper: v0.7 base + wq-013 (kernel.sched_util_clamp_min=128)
# Auto-generated by queue worker for integration check.
# Usage: --apply-temp | --undo

set -euo pipefail

ACTION=${1:-"--help"}
BASE_PRESET="$(dirname "${BASH_SOURCE[0]}")/tao-os-presets-v0.7.sh"

if [[ -z "${TAO_SUDO_PASS:-}" ]]; then
    read -rsp "[CursiveOS] sudo password: " TAO_SUDO_PASS && echo
fi
export TAO_SUDO_PASS
SP="$TAO_SUDO_PASS"
s() { echo "$SP" | sudo -S "$@" 2>/dev/null || true; }

STATE_FILE="$HOME/TAO-OS/preset_state_backup_integration_wq013.txt"

if [[ "$ACTION" == "--apply-temp" ]]; then
    echo "Applying v0.7 base presets..."
    bash "$BASE_PRESET" --apply-temp

    echo "Applying wq-013: kernel.sched_util_clamp_min=128..."
    # Save original value
    ORIG=$(sysctl -n kernel.sched_util_clamp_min 2>/dev/null || echo "N/A")
    echo "sched_util_clamp_min: $ORIG" > "$STATE_FILE"

    if sysctl -n kernel.sched_util_clamp_min &>/dev/null; then
        s sysctl -w kernel.sched_util_clamp_min=128 \
            && echo "✓ kernel.sched_util_clamp_min=128 applied" \
            || echo "  WARNING: sched_util_clamp_min write failed"
    else
        echo "ERROR: kernel.sched_util_clamp_min does not exist on this kernel"
        exit 1
    fi

elif [[ "$ACTION" == "--undo" ]]; then
    echo "Reverting wq-013 tweak..."
    if [[ -f "$STATE_FILE" ]]; then
        ORIG=$(grep "sched_util_clamp_min:" "$STATE_FILE" | cut -d':' -f2 | xargs)
        [[ -n "$ORIG" && "$ORIG" != "N/A" ]] && s sysctl -w kernel.sched_util_clamp_min="$ORIG" 2>/dev/null || true
        rm -f "$STATE_FILE"
        echo "✓ wq-013 tweak reverted"
    fi
    echo "Reverting v0.7 base presets..."
    bash "$BASE_PRESET" --undo
else
    echo "Usage: $0 --apply-temp | --undo"
    exit 1
fi
